### ISSUE TITLE
Argon2id as cache-hard function.

### ISSUE THREAD

**Issue by funny-falcon** [epixoip/pufferfish#6]
As I understand, main concern agains Argon2id is that it is "memory-hard" function, ie it consumes a lot of memory, but memory access is slow on regular computer even more than on ASIC.

But Argon2id is itself quite tunable. Will it be feasible to use Argon2id with low memory consumption (ie 256kB) and many-many rounds as a cache-hard function?

**Comment by Sc00bz** [comment]
Cache hard algorithms are hard because of small random look ups (GPUs don't like that). Memory hard algorithms are hard because of memory bandwidth (GPUs have lots of that). These are similar but work very differently.

So no, but if you want you can benchmark optimized versions of both as a defender and as an attacker to see if I'm wrong.

**Comment by Sc00bz** [comment]
I was just thinking about this, and I was fairly confident that you don't need a GPU benchmark if you benchmark the CPU correctly and there's not much difference in speed between staying in cache and hitting memory:
```
i5-6500 3.2 GHz, Dual Channel DDR4-2133 (Timing 16-15-15-36) Desktop (averaged over 10 runs):
Argon2id m=131072, t=16,    p=1: 1.838s
Argon2id m=65536,  t=32,    p=1: 1.776s
Argon2id m=32768,  t=64,    p=1: 1.715s
Argon2id m=16384,  t=128,   p=1: 1.720s
Argon2id m=8192,   t=256,   p=1: 1.660s

Argon2id m=256,    t=8192,  p=1: 1.446s
Argon2id m=128,    t=16384, p=1: 1.455s


i5-6200U 2.3GHz, Single Channel DDR3-1600 (Timing 11-11-11-28) Laptop (averaged over 3 runs):
Argon2id m=131072, t=16,    p=1: 2.454s
Argon2id m=65536,  t=32,    p=1: 2.377s
Argon2id m=32768,  t=64,    p=1: 2.318s
Argon2id m=16384,  t=128,   p=1: 2.261s
Argon2id m=8192,   t=256,   p=1: 2.189s

Argon2id m=256,    t=8192,  p=1: 1.875s
Argon2id m=128,    t=16384, p=1: 1.872s


Q9300 2.5GHz, Dual Channel DDR2-800 (Timing 5-5-5-18) Desktop (averaged over 3 runs):
Argon2id m=131072, t=16,    p=1: 5.842s
Argon2id m=65536,  t=32,    p=1: 5.763s
Argon2id m=32768,  t=64,    p=1: 5.679s
Argon2id m=16384,  t=128,   p=1: 5.614s
Argon2id m=8192,   t=256,   p=1: 5.574s

Argon2id m=256,    t=8192,  p=1: 5.051s
Argon2id m=128,    t=16384, p=1: 5.024s
```

It is only 27% (i5-6500), 31% (i5-6200U), and 16% (Q9300 [Note this CPU doesn't have L3 cache like the others]) faster when you stay in L2 cache (256 KiB) vs hitting memory (128 MiB). This is likely because Argon2's bottleneck is computations instead of memory bandwidth, and Argon2 look ups are not evenly distributed on purpose to get a higher cache hit rate. For this to be a cache-hard algorithm it should be much faster in cache likely 5x-10x faster, depending on RAM latency vs CPU speed (and cache hit rates). You can find out by benchmarking Pufferfish2 with `m=17, t=1` and `m=8, t=11`. You might need to go with a higher `t` to average out the initial fill (next is `m=17, t=3` and `m=8, t=12` then add 1 to both `t`s for a close amount of work [~25% difference then halves with each increase]). Ignoring the initial fill and some other small things, cost is `2**cost_m*(2**cost_t+2)`. So `m=8, t=11` does about 0.1% more work than `m=17, t=1` (ie the same).

I'm lazy and used PHP 7.4.8 but might actually be better because we're talking about auth and it's likely running in PHP. Note the PHP overhead is very small since Argon2 was running for over a second.

**Comment by funny-falcon** [comment]
I've got almost same result for Go's implementation of Argon2id (it is implemented in assembly, therefore it is fast).

> Argon2 look ups are not evenly distributed on purpose to get a higher cache hit rate

Argon2 lookups are quite random. But they are large: 1024byte at once. Looks like adaptive prefetching makes it reasonably fast.

But if Argon2 is bound by computation performance (on CPU), and it uses most performant instructions for that, then ASIC advantage in computation speed will be quite limited, won't it? And then memory hardness is the right thing to make competetive ASIC as expensive as possible.

I don't say anything against cache-hardness. But looks like both concepts are equally capable to pretect against ASIC's brute force.

Probably, truth is in their hybrid?

**Comment by Sc00bz** [comment]
> > Argon2 look ups are not evenly distributed on purpose to get a higher cache hit rate
> 
> Argon2 lookups are quite random. But they are large: 1024byte at once. Looks like adaptive prefetching makes it reasonably fast.

Random look ups are done something like `blockId = (((value * value) >> 32) * numBlocks) >> 32` (too lazy to look at the code). Actually I know where it basically is ah: https://github.com/P-H-C/phc-winner-argon2/tree/440ceb9612d5a20997e3e12728542df2de713ca4/src/core.c#L239-L242. This makes cache hits higher.

> But if Argon2 is bound by computation performance (on CPU), and it uses most performant instructions for that, then ASIC advantage in computation speed will be quite limited, won't it? And then memory hardness is the right thing to make competetive ASIC as expensive as possible.

ASICs will always have a speed advantage. It's all about getting the most out of the hardware you have.

> Probably, truth is in their hybrid?

Yes, hybrid would be best, but normally it just makes an algorithm that's either or neither and not both.

**Comment by funny-falcon** [comment]
> Random look ups are done something like `blockId = (((value * value) >> 32) * numBlocks) >> 32` (too lazy to look at the code). 

I thought to complain that since `value` (`pseudo_rand`) is 64bit then it is fair uniform random but... `value` is really 32bit:
https://github.com/P-H-C/phc-winner-argon2/blob/3df7b847b1725e64c577a6d6db7dd6cbfcc050d2/src/ref.c#L174

And with this fact it become `frac=(value/(1<<32)); blockid = numBlocks * (frac*frac);` , where `0<=frac<1`, and it is certainly biased towards zero. And resulsting index is biased towards fresh computed value (since there is next step is `blockid = numBlocks - 1 - blockid`).

Therefore you are totally correct.
